config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root 'shorteners#new'
  
  resources :shorteners, only: [:index, :new, :create]

  mount Sidekiq::Web, at: "/sidekiq"

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end

  get '/:short_url', to: 'shorteners#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortener.rb
class Shortener < ApplicationRecord
  before_validation :generate_short_url, on: :create
  
  validates :full_url, :short_url, presence: true
  validates :short_url, uniqueness: true
  validates :full_url, url: true, allow_blank: true
  
  after_create :crawl_for_title

  def self.top_100
    Shortener.order(counter: :desc, created_at: :asc).limit(100)
    # Shortener.order("counter DESC NULLS LAST").limit(100) #for postgresql in case default counter is null
  end

  def full_url_redirect
    UrlUtil.with_protocol self.full_url
  end

  private

  def generate_short_url
    self.short_url = UrlUtil.shortening_algorithm next_number_for_shortening_sequence
  end

  def next_number_for_shortening_sequence
    (Shortener.last&.id || 0) + 1
  end

  def crawl_for_title
    Shortener::TitleCrawlerWorker.perform_async(self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found_response

  private

  def render_not_found_response exception
    render file: "#{Rails.root}/public/404.html", status: :not_found#404
  end
end

app/controllers/shorteners_controller.rb
class ShortenersController < ApplicationController
  before_action :get_shortener, only: [:show]

  def index
    @shorteners = Shortener.top_100
  end

  def new
  end

  def show
    @shortener.increment!(:counter)
    redirect_to @shortener.full_url_redirect
  end

  def create
    @shortener = Shortener.new(shortener_params)

    respond_to do |format|
      if @shortener.save
        format.js { render :create, status: :created }
      else
        format.js { render create: @shortener.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def get_shortener
    @shortener = Shortener.find_by!(short_url: params[:short_url])
  end
  
  def shortener_params
    params.require(:shortener).permit(:full_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shorteners_helper.rb
module ShortenersHelper

  def short_url_display short_url
    "#{request.protocol}#{request.host_with_port}/#{short_url}"
  end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning mt-5" role="alert">
    <ul style='margin-bottom: 0px'>
      <% object.errors.full_messages.each do |msg| %>
        <%= content_tag :li, msg if msg.is_a?(String) %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compendium</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row text-center mt-2 mb-3">
        <h1>Compendium - URL Shortener</h1>
        <div class='row text-center'>
          <%= link_to "Hottest URL's", shorteners_url, {class: 'link-secondary'} %>
          <%= link_to "URL Shortener", "/", {class: 'link-secondary'} %>
        </div>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shorteners/_short_url_display.html.erb
<% if @shortener&.persisted? %>
  <div class='container short_diplay_box mt-5 mb-5''>
    <div class='row'>
      <div class='col-12 text-center'>
        <h3 class='short-url-text'><%= short_url_display @shortener.short_url %></h3>
      </div>
      
    </div>
    <div class='row'>
      <div class='col-12 text-center'>
        <a class='btn btn-dark mt-4' onclick='copyUrl()'> Copy </a>
      </div>
    </div>
  </div>
<% end %>

<script>
  function copyUrl() {
    var copyText = $(".short-url-text").text();
    navigator.clipboard.writeText(copyText);
  }
</script>

app/views/shorteners/create.js.erb
<% if @shortener.valid? %>
  $("#short_url_display").html("<%=escape_javascript(render( partial: "short_url_display"))%>");
<% else %>
  $("#short_url_display").html("<%=escape_javascript(render( partial: "layouts/errors", locals: {object: @shortener}))%>");
<% end %>

app/views/shorteners/index.html.erb
<table class="table table-responsive table-striped">
  <thead>
    <tr>
      <th style='width: 10%;'>Rank</th>
      <th>Short URL</th>
      <th>Full URL</th>
      <th>Title</th>
      <th style='width: 10%;'>Accesses</th>
    </tr>
  </thead>
  <tbody>
    <% @shorteners.each_with_index do |shortener, index| %>
      <tr>
        <td><%=index+1%></td>
        <td><%= short_url_display shortener.short_url %></td>
        <td><%= truncate(shortener.full_url_redirect, length: 65) %></td>
        <td><%= truncate(shortener.html_title, length: 65)%></td>
        <td><%= shortener.counter %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shorteners/new.html.erb
<div id='shortener_container'>
  <%= form_with(model: Shortener.new, local: false) do |shortener_form| %>
    <div class="row col-10 offset-1">
      <div class="input-group mb-3 col-3">
        <%= shortener_form.text_field :full_url, {class: 'form-control', placeholder: 'Type your full URL here.'} %>
      </div>
    </div>

    <div class="row col-10 offset-1">
      <%= shortener_form.submit "Get your short URL!", {class: 'btn btn-info'} %>
    </div>
  <% end %>

  <div id='short_url_display'>
  
  </div>
</div>